from enum import StrEnum


class LoginStatus(StrEnum):
    SUCCESS = "SUCCESS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    PASSWORD_REQUIRED = "PASSWORD_REQUIRED"
    SEND_OTP = "SEND_OTP"
    REGISTER_WITH_OTP = "REGISTER_WITH_OTP"
    